sudo: required
services:
  - docker
before_install:
  - docker build -t seandolan/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true seandolan/react-test yarn test

after_success:
  - docker build -t seandolan/multi-client ./client
  - docker build -t seandolan/multi-nginx ./nginx
  - docker build -t seandolan/multi-server ./server
  - docker build -t seandolan/multi-worker ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push into Docker Hub
  - docker push seandolan/multi-client
  - docker push seandolan/multi-nginx
  - docker push seandolan/multi-server
  - docker push seandolan/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-556349070138
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY